//
// PATTERN

export const PATTERN_SET_PATTERN = 'PATTERN_SET_PATTERN';

export const PATTERN_UPDATE_SETTING = 'PATTERN_UPDATE_SETTING';

export const PATTERN_RE_SEED_LAYERS = 'PATTERN_RE_SEED_LAYERS';
export const PATTERN_RESET_DRAW_FOR_LAYERS = 'PATTERN_RESET_DRAW_FOR_LAYERS';

export const PATTERN_CREATE_LAYER = 'PATTERN_CREATE_LAYER';
export const PATTERN_CREATE_LAYERS = 'PATTERN_CREATE_LAYERS';
export const PATTERN_UPDATE_LAYER = 'PATTERN_UPDATE_LAYER';
export const PATTERN_DELETE_LAYER = 'PATTERN_DELETE_LAYER';

export const PATTERN_SET_THEME = 'PATTERN_SET_THEME';

//
// PATTERNS

export const GALLERY_LOAD_PATTERNS = 'GALLERY_LOAD_PATTERNS';
export const GALLERY_LOAD_PATTERNS_SUCCESS = 'GALLERY_LOAD_PATTERNS_SUCCESS';
export const GALLERY_LOAD_PATTERNS_FAIL = 'PATTERNS_LOAD_PATTERNS_FAIL';
export const GALLERY_SET_PATTERN_SELECTED = 'GALLERY_LOAD_PATTERNS_FAIL';
