//
// PATTERN

export const PATTERN_UPDATE_SETTING = 'PATTERN_UPDATE_SETTING';

export const PATTERN_RE_SEED_LAYERS = 'PATTERN_RE_SEED_LAYERS';
export const PATTERN_RESET_DRAW_FOR_LAYERS = 'PATTERN_RESET_DRAW_FOR_LAYERS';

export const PATTERN_CREATE_LAYER = 'PATTERN_CREATE_LAYER';
export const PATTERN_CREATE_LAYERS = 'PATTERN_CREATE_LAYERS';
export const PATTERN_UPDATE_LAYER = 'PATTERN_UPDATE_LAYER';
export const PATTERN_DELETE_LAYER = 'PATTERN_DELETE_LAYER';

export const PATTERN_SET_THEME = 'PATTERN_SET_THEME';

//
// PATTERNS

export const PATTERNS_LOAD = 'PATTERNS_LOAD';
export const PATTERNS_LOAD_SUCCESS = 'PATTERNS_LOAD_SUCCESS';
export const PATTERNS_LOAD_FAIL = 'PATTERNS_LOAD_FAIL';
