
//
// EDITOR

export const EDITOR_UPDATE_SETTING  = 'EDITOR_UPDATE_SETTING';

export const EDITOR_CREATE_LAYER    = 'EDITOR_CREATE_LAYER';
export const EDITOR_UPDATE_LAYER    = 'EDITOR_UPDATE_LAYER';
export const EDITOR_DELETE_LAYER    = 'EDITOR_DELETE_LAYER';
